models/Doer.php
<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "doer".
 *
 * @property integer $id
 * @property string $snp
 * @property string $phone
 * @property string $email
 * @property string $skype
 * @property integer $city_id
 * @property string $education
 * @property integer $main_professions
 * @property string $other_professions
 * @property string $specific
 * @property string $comment
 * @property double $middle_mark
 * @property integer $projects_count
 *
 * @property Cities $city
 * @property Profession $mainProfession
 */
class Doer extends \yii\db\ActiveRecord
{
    public $criterions;
    public $black;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'doer';
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {//если заказ завершен то ставим дату изменения на дату фактическую
            $this->other_professions = json_encode($this->other_professions);
            $this->main_professions = json_encode($this->main_professions);

            return true;
        } else {
            return false;
        }
    }

    public function afterFind()
    {
        $this->other_professions = json_decode($this->other_professions);
        $this->main_professions = json_decode($this->main_professions);
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['snp', 'email'], 'required'],
            [['city_id', 'projects_count'], 'integer'],
            [['specific', 'comment'], 'string'],
            [['middle_mark'], 'number'],
            [['snp', 'phone', 'email', 'skype', 'education'], 'string', 'max' => 255],
            [['snp'], 'unique'],
            [['email'], 'unique'],
            [['other_professions', 'main_professions','criterions'], 'safe'],
            [['city_id'], 'exist', 'skipOnError' => true, 'targetClass' => Cities::className(), 'targetAttribute' => ['city_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'snp' => 'ФИО',
            'phone' => 'Телефон',
            'email' => 'Email',
//            'skype' => 'Скайп',
            'middle_mark' => 'Средний бал',
            'city_id' => 'Город',
            'education' => 'Образование',
            'main_professions' => 'Основная специализация',
            'other_professions' => 'второстепенные специализации',
            'specific' => 'Узкая специализация',
            'comment' => 'Примечание',
            'projects_count' => 'Количество проектов',
            'black' => 'В черный список'
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
//    public function getCity()
//    {
//        return $this->hasOne(Cities::className(), ['id' => 'city_id']);
//    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProjects()
    {
        return $this->hasMany(Project::className(), ['doer_id' => 'id']);
    }


    /**
     * Получаем id всех профессий (основных и второстепенных) исполнителя
     * @return array
     */
    public function getProfessionsId()
    {
        $mainProfessions = $this->main_professions;
        return array_unique(array_merge($mainProfessions, $this->other_professions ? $this->other_professions : []));
    }

    /**
     * Возвращает список моделей городов
     * @return mixed
     */
    public function getCitiesList()
    {
        return ArrayHelper::map(Cities::find()->all(), 'id', 'name');
    }

    /**
    * Возвращает список моделей специализаций
    * @return mixed
    */
    public function getProfessionList()
    {
        return ArrayHelper::map(Profession::find()->all(), 'id', 'name');
    }

    /**
     * Возвращает список моделей специализаций
     * @return mixed
     */
    public function getProfessionListForSearch()
    {
        $array = ArrayHelper::map(Profession::find()->all(), 'id', 'name');
        $newArray = [];

        foreach ($array as $key => $value){
            $newArray['"'.$key.'"'] = $value;
        }

        return $newArray;
    }

    public function getFreeProjects()
    {
        $doerProjects = DoerProject::find()->where(['doer_id' => $this->id])->groupBy('project_id')->all();
        $freeProjects = Project::find();

        foreach($doerProjects as $project)
        {
            $freeProjects->andWhere(['!=', 'id', $project->project_id]);
        }


        return ArrayHelper::map($freeProjects->all(), 'id', 'name');
    }

    public function getCriterions(){
            return ArrayHelper::map(Criterions::find()->all(), 'id', 'name');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMarks()
    {
        return $this->hasMany(Mark::className(), ['doer_id' => 'id']);
    }

    public function getMarksByProject($project_id)
    {
        return Mark::find()->where(['doer_id' => $this->id, 'project_id' => $project_id])->all();
    }


}

models/Mark.php
<?php

namespace app\models;

use app\services\MarksManager;
use Yii;

/**
 * This is the model class for table "mark".
 *
 * @property integer $id
 * @property double $mark
 * @property integer $criterion_id
 * @property integer $project_id
 * @property integer $profession_id
 * @property integer $doer_id
 * @property Criterions $criterion
 * @property Project $project
 */
class Mark extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'mark';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['mark', 'criterion_id', 'project_id', 'profession_id', 'doer_id'], 'required'],
            [['mark'], 'number'],
            [['criterion_id', 'project_id'], 'integer'],
            [['criterion_id'], 'exist', 'skipOnError' => true, 'targetClass' => Criterions::className(), 'targetAttribute' => ['criterion_id' => 'id']],
            [['project_id'], 'exist', 'skipOnError' => true, 'targetClass' => Project::className(), 'targetAttribute' => ['project_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'mark' => 'Mark',
            'criterion_id' => 'Criterion ID',
            'project_id' => 'Project ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCriterion()
    {
        return $this->hasOne(Criterions::className(), ['id' => 'criterion_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProject()
    {
        return $this->hasOne(Project::className(), ['id' => 'project_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProfession()
    {
        return $this->hasOne(Profession::className(), ['id' => 'profession_id']);
    }
}

controllers/DoerController.php
<?php

namespace app\controllers;

use app\models\AddProjectForm;
use app\models\Cities;
use app\models\DoerProject;
use app\models\Project;
use app\models\ProjectSearch;
use app\models\User;
use app\services\MarksManager;
use Yii;
use app\models\Doer;
use app\models\DoerSearch;
use yii\data\ArrayDataProvider;
use yii\db\Query;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use app\models\Mark;
use app\models\DoerMiddleMarks;
use app\models\Criterions;

/**
 * DoerController implements the CRUD actions for Doer model.
 */
class DoerController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['index', 'create', 'update', 'view'],
                'rules' => [
                    // allow authenticated users
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    // everything else is denied
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Doer models.
     * @return mixed
     */
    public function actionIndex()
    {
        $model = new Doer();
        $searchModel = new DoerSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $id = '';
        $crit = '';


       if(Yii::$app->request->post('Doer')){
         $post =  Yii::$app->request->post('Doer');

           $id = $post['main_professions'];
           $crit = $post['criterions'];


           $dataProvider->query
               ->leftJoin('mark', 'mark.doer_id = doer.id')
               ->groupBy('doer_id')
               ->orderBy(['mark'=> SORT_DESC]);

           if($crit != null)
           {
               $dataProvider->query->andFilterWhere(['criterion_id' => $crit]);
           }else{
               $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
           }

           if($id != null)
           {
               $dataProvider->query->andFilterWhere(['or', ['like', 'main_professions', '"'.$id.'"'], ['like', 'other_professions', '"'.$id.'"']]);
           }

           $headers = Yii::$app->response->headers;
//           Yii::info($headers->get('content-type'), 'doer');
//           if ($headers->get('Expires')!=null)
//               $headers = $headers->remove('Expires');
//           if ($headers->get('Cache-Control')!=null)
//               $headers = $headers->remove('Cache-Control');
//           if ($headers->get('Pragma')!=null)
//               $headers = $headers->remove('Pragma');
//           if ($headers->get('Last-Modified')!=null)
//               $headers = $headers->remove('Last-Modified');
       }

//        session_start();
        header_remove("Expires");
        header_remove("Cache-Control");
        header_remove("Pragma");
        header_remove("Last-Modified");

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'id' => $id,
            'crit' => $crit,
            'model' => $model
        ]);
    }

    /**
     * DEPRECATED
     * Привязывает проект к пользователю
     * @param $doer_id
     * @param $project_id
     * @return bool
     */
    public function actionAddProject($doer_id, $project_id)
    {
        $project = Project::findOne($project_id);
        if($project == null)
            throw new NotFoundHttpException('Запрашиваемого проекта не существует.');

        $marksManager = new MarksManager($project);
        $marksManager->updateMarks($doer_id);

        $doerProject = new DoerProject();
        $doerProject->saveRelation($doer_id, $project_id);

        return true;
    }

    /**
     * Displays a single Doer model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {   
        $request = Yii::$app->request;
        $user = User::findOne(['id' => Yii::$app->user->getId()]);
        $ordersSearchModel = new ProjectSearch();
        $ordersDataProvider = $ordersSearchModel->searchWithDoer(Yii::$app->request->queryParams, $id);

        return $this->render('view', [
            'model' => $this->findModel($id),
            'ordersSearchModel' => $ordersSearchModel,
            'ordersDataProvider' => $ordersDataProvider,
            'doer_id' => $id,
            'user' => $user,
        ]);
    }

    public function actionTest($id)
    {
        $model = $this->findModel($id);

        echo $model->getProfessionsId();
        exit;
    }

    /**
     * Creates a new Doer model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new Doer();  

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Добавить исполнителя",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Создать',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }else if($model->load($request->post()) && $model->save()){
                return [
                    'forceReload'=>'#crud-datatable-pjax',
                    'title'=> "Добавить исполнителя",
                    'content'=>'<span class="text-success">Создание исполнителя успешно завершено</span>',
                    'footer'=> Html::button('ОК',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::a('Создать еще',['create'],['class'=>'btn btn-primary','role'=>'modal-remote'])
        
                ];         
            }else{           
                return [
                    'title'=> "Добавить исполнителя",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Создать',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }
       
    }

    public function actionAdd($id)
    {
        return [
            'forceReload'=>'#crud-datatable-pjax',
            'title'=> "исполнитель #".$id,
            'content'=>'<span class="text-success">Добавлен в черный список</span>',
            'footer'=> Html::button('ОК',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"])
        ];
    }

    /**
     * Добавляет проект исполнителю
     * @param $doer_id
     * @return array
     */
    public function actionTakeProject($doer_id)
    {
        $request = Yii::$app->request;
        $model = new AddProjectForm($doer_id);
        $doer = Doer::findOne($doer_id);

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Добавить проект",
                    'content'=>$this->renderAjax('take_project', [
                        'model' => $model,
                        'doer' => $doer,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                        Html::button('Привязать',['class'=>'btn btn-primary','type'=>"submit"])

                ];
            }else if($model->load($request->post()) && $model->addProject()){
                return [
                    'forceReload'=>'#crud-datatable-pjax',
                    'title'=> "Добавить проект",
                    'content'=>'<span class="text-success">Заказ успешно привязан к исполнителю</span>',
                    'footer'=> Html::button('ОК',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"])

                ];
            }else{
                return [
                    'title'=> "Добавить проект",
                    'content'=>$this->renderAjax('take_project', [
                        'model' => $model,
                        'doer' => $doer,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                        Html::button('Привязать',['class'=>'btn btn-primary','type'=>"submit"])

                ];
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {

views/doer/_columns.php
<?php
use app\models\Cities;
use yii\helpers\Html;
use yii\helpers\Url;

return [
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '15px',
    ],
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '20px',
    ],
        // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'id',
    // ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'snp',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'phone',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'email',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'middle_mark',
        'width' => '10px',
    ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'education',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'main_professions',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'other_professions',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'specific',
    // ],
    //[
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'comment',
//    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'main_professions',
        'value' => function($model){

            $id = (is_array($model)) ? $model['id'] : $model->id;
            if(is_array($model)) {
               $ot_pref = json_decode($model['main_professions']);
            }else{
                $ot_pref = $model['main_professions'];
            }

            $mark = '';
            if(!empty($ot_pref)){
            foreach($ot_pref as $pr){
              $profName =  \app\models\Profession::find()->select('*')->where(['id' => $pr])->one();

                $doerMiddleMarks = \app\models\DoerMiddleMarks::find('*')->where(['profession_id' => $profName->id])->andWhere(['doer_id' => $id])->one();
                        if($doerMiddleMarks == null){
                            $mark .= ' '.$profName->name.'(0)';
                        }else{
                            $mark .= ' '.$profName->name.'('.$doerMiddleMarks->middle_mark.'),';
                        }


            }
            }

            return $mark;
        },
        'filterInputOptions' => [
            'class' => 'form-control',
            'prompt' => 'Все',
        ],
        'filter'=> $model->getProfessionListForSearch(),
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'other_professions',
        'value' => function($model){
            $id = (is_array($model)) ? $model['id'] : $model->id;
            if(is_array($model)) {
                $ot_pref = json_decode($model['other_professions']);
            }else{
                $ot_pref = $model['other_professions'];
            }

            $mark = '';
            if(!empty($ot_pref)){
                foreach($ot_pref as $pr){
                    $profName =  \app\models\Profession::find()->select('*')->where(['id' => $pr])->one();
                    $doerMiddleMarks = \app\models\DoerMiddleMarks::find('middle_mark')->where(['profession_id' => $profName->id])->andWhere(['doer_id' => $id])->one();
                    if($doerMiddleMarks == null){
                        $mark .= ' '.$profName->name.'(0)';
                    }else{
                        $mark .= ' '.$profName->name.'('.$doerMiddleMarks->middle_mark.'),';
                    }
                }
            }
            return $mark;
        },
        'filterInputOptions' => [
            'class' => 'form-control',
            'prompt' => 'Все',
        ],
        'filter'=> $model->getProfessionListForSearch(),

    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'projects_count',
        'width' => '5px',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'city_id',
        'value' => function($model){
            $id = (is_array($model)) ? $model['city_id'] : $model->city_id;

            $city = Cities::find()->where(['id' => $id])->one();

            return $city['name'];
        },
        'filterInputOptions' => [
            'class' => 'form-control',
            'prompt' => 'Все',
        ],
        'filter'=> $model->getCitiesList(),
        'header' => 'Город',

    ],
    [

        'attribute'=>'black',
        'content' => function($model){

                $bl = \app\models\BlackList::findOne(['block_id' => $model->id]);
                if($bl){
                    return '<b class="text-danger">Уже В черном списке!</b>';
                }
            return Html::a('<span class="fa fa-ban"> В черный список</span>', ['black-list/pluse','id' => $model->id]);
        },
        'format' => 'raw',



    ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign'=>'middle',
        'urlCreator' => function($action, $model, $key, $index) { 
                return Url::to([$action,'id'=>$key]);
        },
        'viewOptions'=>['title'=>'View','data-toggle'=>'tooltip'],
        'updateOptions'=>['role'=>'modal-remote','title'=>'Сохранить', 'data-toggle'=>'tooltip'],
        'deleteOptions'=>['role'=>'modal-remote','title'=>'Удалить',
                          'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                          'data-request-method'=>'post',
                          'data-toggle'=>'tooltip',
                          'data-confirm-title'=>'Вы уверены?',
                          'data-confirm-message'=>'Вы действительно хотите удалить данный элемент?'],
    ],

];   

views/doer/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model app\models\Doer */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="doer-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'snp')->textInput(['maxlength' => true]) ?>

    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'phone')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'skype')->textInput(['maxlength' => true]) ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'city_id')->dropDownList($model->getCitiesList()) ?>
        </div>
    </div>

    <?= $form->field($model, 'education')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'main_professions')->widget(Select2::classname(), [
        'data' => $model->getProfessionList(),
        'options' => ['placeholder' => 'Выберите ...'],
        'pluginEvents' => [
            "change" => "function() 
						{
							
						}",
        ],
        'pluginOptions' => [
            'allowClear' => true,
            'multiple' => true,
        ],
    ]);?>

    <?= $form->field($model, 'other_professions')->widget(Select2::classname(), [
        'data' => $model->getProfessionList(),
        'options' => ['placeholder' => 'Выберите ...'],
        'pluginEvents' => [
            "change" => "function() 
						{
							
						}",
        ],
        'pluginOptions' => [
            'allowClear' => true,
            'multiple' => true,
        ],
    ]);?>

    <?= $form->field($model, 'specific')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'comment')->textarea(['rows' => 6]) ?>


	<?php if (!Yii::$app->request->isAjax){ ?>
	  	<div class="form-group">
	        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	    </div>
	<?php } ?>

    <?php ActiveForm::end(); ?>
    
</div>

views/doer/_marks.php
<?php
/**
 * Created by PhpStorm.
 * User: Ilusha
 * Date: 02.05.2017
 * Time: 17:36
 */

$doerMiddleMarks = \app\models\DoerMiddleMarks::find()->where(['doer_id' => $doer_id])->all();

?>

<table id="w0" class="table table-striped table-bordered detail-view"><tbody>
    <?php foreach($doerMiddleMarks as $middleMark): ?>
        <tr><th><?=$middleMark->profession->name?></th><td><?=$middleMark->middle_mark?></td></tr>
    <?php endforeach; ?>
</tbody></table>,

views/doer/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Doer */

?>
<div class="doer-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/doer/take_project.php
<?php
/**
 * Created by PhpStorm.
 * User: Ilusha
 * Date: 02.05.2017
 * Time: 6:34
 */

use yii\widgets\ActiveForm;
use yii\helpers\Html;

?>

<div class="doer-take_order">
    <div class="doer-take_order-form">

        <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'project_id')->dropDownList($doer->freeProjects) ?>

        <?php if (!Yii::$app->request->isAjax){ ?>
            <div class="form-group">
                <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            </div>
        <?php } ?>

        <?php ActiveForm::end(); ?>

    </div>
</div>

views/doer/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Doer */
?>
<div class="doer-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/doer/view.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset;
use johnitvn\ajaxcrud\BulkButtonWidget;
use yii\widgets\DetailView;
use rmrevin\yii\module\Comments;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ProjectSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = "Проекты";
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);

?>
<div class="panel panel-inverse project-index">
    <div class="panel-heading">
        <!--        <div class="panel-heading-btn">-->
        <!--        </div>-->
        <h4 class="panel-title"><?=$model->snp?></h4>
    </div>
    <div class="panel-body">
        <div id="ajaxCrudDatatable">

            <?= Comments\widgets\CommentListWidget::widget([
                'entity' => (string)"task-{$model->id}",// type and id
                'showDeleted' => false,
                'showCreateForm' => $user->role == 'admin' ? true : false,
            ]); ?>
            <hr />
            <?=GridView::widget([
                'id'=>'crud-datatable',
                'dataProvider' => $ordersDataProvider,
                'filterModel' => $ordersSearchModel,
                'pjax'=>true,
                'pjaxSettings'=>[
                    'neverTimeout'=>true,
                    'beforeGrid'=> DetailView::widget([
                        'model' => $model,
                        'attributes' => [
                            'snp',
                            'middle_mark',
                            'phone',
                            'email:email',
                            'projects_count',
                        ],
                    ]).$this->render('_marks', ['doer_id' => $doer_id]),
                ],
                'columns' => require(__DIR__.'/_orders_columns.php'),
                'toolbar'=> [
                    ['content'=>
                        Html::a('<i class="glyphicon glyphicon-plus"></i>', ['doer/take-project', 'doer_id' => $doer_id],
                            ['role'=>'modal-remote','title'=> 'Привязать проект','class'=>'btn btn-default']).
                        Html::a('<i class="glyphicon glyphicon-repeat"></i>', ['', 'id' => $doer_id],
                            ['data-pjax'=>1, 'class'=>'btn btn-default', 'title'=>'Обновить']).
                        '{toggleData}'.
                        '{export}'
                    ],
                ],
                'striped' => true,
                'condensed' => true,
                'responsive' => true,
                'panel' => [
                    'headingOptions' => ['style' => 'display: none;'],
                    'after'=>BulkButtonWidget::widget([
                            'buttons'=>Html::a('<i class="glyphicon glyphicon-trash"></i>&nbsp; Удалить',
                                ["project/bulk-delete"],
                                [
                                    "class"=>"btn btn-danger btn-xs",
                                    'role'=>'modal-remote-bulk',
                                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                                    'data-request-method'=>'post',
                                    'data-confirm-title'=>'Вы уверены?',
                                    'data-confirm-message'=>'Вы действительно хотите удалить данный элемент?'
                                ]),
                        ]).
                        '<div class="clearfix"></div>',
                ]
            ])?>
        </div>

    </div>
</div>


<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "footer"=>"",// always need it for jquery plugin
])?>+
<?php Modal::end(); ?>